%defines
%locations
%define parse.error verbose

%{
#include <stdio.h>
#include <stddef.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
extern FILE *yyin;
extern char *yytext;
int yylex(void);
void yyerror(const char *s);
%}

%union {
    int ival;
    char* str;
};

/* Tokens */
%token <str> ARRAYCLOSE
%token <str> ARRAYOPEN
%token <str> BASEFONT
%token <str> CATALOG
%token <str> CONTENTS
%token <str> COUNT
%token <str> COURIER
%token <str> CREATIONDATE
%token <str> DIFFERENCES
%token <str> ENCODING
%token <str> ENDOBJ
%token <str> FONE
%token <str> FONT
%token <str> GREATERTHAN
%token <str> INFO
%token <str> KIDS
%token <str> KIDSLOOP
%token <str> LENGTH
%token <str> LESSTHAN
%token <str> MEDIABOX
%token <str> NAME
%token <str> NEWLINE
%token <str> NUM
%token <str> NUMBERLOOP
%token <str> OBJ
%token <str> OBJREF
%token <str> PAGES
%token <str> PARENT
%token <str> PDFDECLARATION
%token <str> PDFSTRING
%token <str> PROCSET
%token <str> PRODUCER
%token <str> RESOURCES
%token <str> ROOT
%token <str> SIZE
%token <str> SLASHWORD
%token <str> SPACE
%token <str> STARTXREF
%token <str> STREAMENDSTREAM
%token <str> STRING
%token <str> SUBTYPE
%token <str> TEXTSTRING
%token <str> TITLE
%token <str> TRAILER
%token <str> TYPE
%token <str> TYPEONE
%token <str> TYPEPAGE
%token <str> XREF

%start main

/* Non-terminals */
%type <str> HeaderSection
%type <str> PagesSection
%type <str> STRING_LIST
%type <str> StartPage
%type <str> TrailerSection
%type <str> WriteHeader_C0
%type <str> WritePages_L0
%type <str> WritePages_L0_L1
%type <str> WritePages_L0_L1_C10
%type <str> WritePages_L0_L1_L2
%type <str> WritePages_L0_L1_L2_B5_C0
%type <str> WritePages_L0_L1_L2_B5_C0_C1
%type <str> WritePages_L0_L1_L2_B5_C0_C1_C2
%type <str> WritePages_L0_L1_L2_C3
%type <str> WritePages_L0_L1_L2_C4
%type <str> WritePages_L0_L1_L2_C5
%type <str> WritePages_L0_L1_L2_C6
%type <str> WritePages_L0_L1_L2_C6_C7
%type <str> WritePages_L0_L1_L2_C6_C8
%type <str> WritePages_L0_L1_L2_C6_ELSE_C9
%type <str> WriteRest_L0

%%
main: HeaderSection PagesSection TrailerSection;
HeaderSection: PDFDECLARATION NEWLINE NUM STRING NUM STRING OBJ NEWLINE LESSTHAN NEWLINE CREATIONDATE STRING_LIST NEWLINE PRODUCER STRING_LIST NUM STRING_LIST NUM STRING_LIST NEWLINE TITLE STRING_LIST NEWLINE GREATERTHAN NEWLINE ENDOBJ NEWLINE NUM STRING NUM STRING OBJ NEWLINE LESSTHAN NEWLINE TYPE STRING CATALOG NEWLINE PAGES STRING NUM STRING NUM STRING_LIST NEWLINE GREATERTHAN NEWLINE ENDOBJ NEWLINE NUM STRING NUM STRING OBJ NEWLINE LESSTHAN NEWLINE TYPE STRING FONT NEWLINE SUBTYPE STRING TYPEONE NEWLINE NAME STRING FONE NEWLINE BASEFONT STRING_LIST NEWLINE WriteHeader_C0 GREATERTHAN NEWLINE ENDOBJ NEWLINE NUM STRING NUM STRING OBJ NEWLINE LESSTHAN NEWLINE STRING FONT STRING LESSTHAN STRING FONE STRING NUM STRING NUM STRING_LIST GREATERTHAN NEWLINE STRING PROCSET STRING ARRAYOPEN STRING PDFSTRING STRING TEXTSTRING STRING ARRAYCLOSE NEWLINE GREATERTHAN NEWLINE ENDOBJ NEWLINE;
PagesSection: WritePages_L0;
STRING_LIST: STRING STRING_LIST | STRING;
StartPage: STRING_LIST NUM STRING OBJ NEWLINE LESSTHAN NEWLINE TYPE STRING TYPEPAGE NEWLINE PARENT STRING NUM STRING NUM STRING_LIST NEWLINE RESOURCES STRING NUM STRING NUM STRING_LIST NEWLINE CONTENTS STRING_LIST NUM STRING_LIST NEWLINE GREATERTHAN NEWLINE ENDOBJ NEWLINE STRING_LIST NUM STRING OBJ NEWLINE LESSTHAN NEWLINE LENGTH STRING_LIST NUM STRING_LIST NEWLINE GREATERTHAN NEWLINE STRING NEWLINE STRING NEWLINE FONE STRING_LIST NEWLINE NUM STRING NUM STRING NUM STRING NUM STRING NUM STRING_LIST NEWLINE STRING_LIST NEWLINE;
TrailerSection: NUM STRING NUM STRING OBJ NEWLINE LESSTHAN NEWLINE TYPE STRING PAGES NEWLINE COUNT STRING_LIST NEWLINE MEDIABOX STRING ARRAYOPEN STRING NUM STRING NUM STRING_LIST ARRAYCLOSE NEWLINE KIDS STRING ARRAYOPEN STRING_LIST NUM STRING_LIST ARRAYCLOSE NEWLINE GREATERTHAN NEWLINE ENDOBJ NEWLINE XREF NEWLINE NUM STRING_LIST NEWLINE NUM STRING NUM STRING_LIST WriteRest_L0 TRAILER NEWLINE LESSTHAN NEWLINE SIZE STRING_LIST NEWLINE ROOT STRING NUM STRING NUM STRING_LIST NEWLINE INFO STRING NUM STRING NUM STRING_LIST NEWLINE GREATERTHAN NEWLINE STARTXREF NEWLINE STRING_LIST NEWLINE STRING_LIST NEWLINE;
WriteHeader_C0: ENCODING STRING LESSTHAN NEWLINE DIFFERENCES STRING ARRAYOPEN STRING NUM STRING_LIST NEWLINE STRING_LIST NEWLINE STRING_LIST NEWLINE STRING_LIST NEWLINE STRING_LIST NEWLINE STRING_LIST SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING_LIST NEWLINE STRING_LIST NEWLINE STRING_LIST NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING_LIST SLASHWORD STRING SLASHWORD STRING_LIST NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING SLASHWORD NEWLINE SLASHWORD STRING SLASHWORD STRING SLASHWORD STRING ARRAYCLOSE NEWLINE GREATERTHAN NEWLINE | /*empty*/;
WritePages_L0: StartPage WritePages_L0_L1 | /*empty*/;
WritePages_L0_L1: WritePages_L0_L1_L2 WritePages_L0_L1_C10 | /*empty*/;
WritePages_L0_L1_C10: NUM STRING NUM STRING NUM STRING NUM STRING_LIST NEWLINE | /*empty*/;
WritePages_L0_L1_L2: STRING WritePages_L0_L1_L2_B5_C0 STRING_LIST NEWLINE WritePages_L0_L1_L2_C3 WritePages_L0_L1_L2_C4 WritePages_L0_L1_L2_C5 WritePages_L0_L1_L2_C6 | /*empty*/;
WritePages_L0_L1_L2_B5_C0: STRING_LIST WritePages_L0_L1_L2_B5_C0_C1 | /*empty*/;
WritePages_L0_L1_L2_B5_C0_C1: STRING WritePages_L0_L1_L2_B5_C0_C1_C2 | /*empty*/;
WritePages_L0_L1_L2_B5_C0_C1_C2: STRING_LIST | /*empty*/;
WritePages_L0_L1_L2_C3: /*empty*/;
WritePages_L0_L1_L2_C4: /*empty*/;
WritePages_L0_L1_L2_C5: /*empty*/;
WritePages_L0_L1_L2_C6: WritePages_L0_L1_L2_C6_C7 WritePages_L0_L1_L2_C6_C8 | WritePages_L0_L1_L2_C6_ELSE_C9;
WritePages_L0_L1_L2_C6_C7: /*empty*/;
WritePages_L0_L1_L2_C6_C8: /*empty*/;
WritePages_L0_L1_L2_C6_ELSE_C9: /*empty*/;
WriteRest_L0: STRING_LIST NUM STRING_LIST | /*empty*/;

%%

    int main(int argc, char ** argv) {
     #ifdef YYDEBUG
            yydebug = 1;
        #endif
        yyin = fopen(argv[1],"r");
        if (yyin == NULL) {
            fprintf(stderr, "Could not open '%s': %s\n", argv[1] , strerror(errno));
            exit(1);
        }
        yyparse();
        int token;
        while ((token = yylex()) != 0) {
            printf("Token: %d (%s)\n", token, yytext);
        }
        return 0;
    }
    
    void yyerror(const char *s) {
        fprintf(stderr, "Error: %s\n", s);
    }
    