%defines
%locations
%error-verbose

%{
#include <stdio.h>
#include <stddef.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
extern FILE *yyin;
extern char *yytext;
int yylex(void);
void yyerror(const char *s);
%}

%union {
    int ival;
    char* str;
};

/* Tokens */
%token <str> ARRAYCLOSE
%token <str> ARRAYOPEN
%token <str> BASEFONT
%token <str> CATALOG
%token <str> CONTENTS
%token <str> COUNT
%token <str> COURIER
%token <str> CREATIONDATE
%token <str> DIFFERENCES
%token <str> ENCODING
%token <str> ENDOBJ
%token <str> FONE
%token <str> FONT
%token <str> GREATERTHAN
%token <str> INFO
%token <str> KIDS
%token <str> KIDSLOOP
%token <str> LENGTH
%token <str> LESSTHAN
%token <str> LESSTHANNEWLINE
%token <str> MEDIABOX
%token <str> NAME
%token <str> NEWLINE
%token <str> NOTDEF
%token <str> NUM
%token <str> NUMBERLOOP
%token <str> OBJ
%token <str> OBJREF
%token <str> PAGES
%token <str> PARENT
%token <str> PDFDECLARATION
%token <str> PDFSTRING
%token <str> PROCSET
%token <str> PRODUCER
%token <str> RESOURCES
%token <str> ROOT
%token <str> SIZE
%token <str> SLASHWORD
%token <str> SPACE
%token <str> STARTXREF
%token <str> STREAMENDSTREAM
%token <str> STRING
%token <str> SUBTYPE
%token <str> TEXTSTRING
%token <str> TITLE
%token <str> TRAILER
%token <str> TYPE
%token <str> TYPEONE
%token <str> TYPEPAGE
%token <str> XREF
%token <str> any
%token <str> character
%token <str> fallback
%token <str> single

%start main

/* Non-terminals */
%type <str> EndPage
%type <str> HeaderSection
%type <str> PagesSection
%type <str> STRING_LIST
%type <str> StartPage
%type <str> TrailerSection
%type <str> WriteHeader_C0
%type <str> WritePages_L0
%type <str> WritePages_L0_L1
%type <str> WritePages_L0_L1_C10
%type <str> WritePages_L0_L1_L2
%type <str> WritePages_L0_L1_L2_B5_C0
%type <str> WritePages_L0_L1_L2_B5_C0_C1
%type <str> WritePages_L0_L1_L2_B5_C0_C1_C2
%type <str> WritePages_L0_L1_L2_C3
%type <str> WritePages_L0_L1_L2_C4
%type <str> WritePages_L0_L1_L2_C5
%type <str> WritePages_L0_L1_L2_C6
%type <str> WritePages_L0_L1_L2_C6_C7
%type <str> WritePages_L0_L1_L2_C6_C8
%type <str> WritePages_L0_L1_L2_C6_ELSE_C9
%type <str> WriteRest_L0

%%
main: HeaderSection PagesSection TrailerSection;
HeaderSection: PDFDECLARATION NEWLINE NUM SPACE NUM SPACE OBJ NEWLINE LESSTHAN NEWLINE CREATIONDATE SPACE STRING_LIST // fallback for any single character NEWLINE PRODUCER SPACE STRING_LIST SPACE STRING SPACE STRING SPACE STRING SPACE NUM STRING // fallback for any single character STRING // fallback for any single character NEWLINE TITLE SPACE STRING_LIST // fallback for any single character NEWLINE GREATERTHAN NEWLINE ENDOBJ NEWLINE NUM SPACE NUM SPACE OBJ NEWLINE LESSTHAN NEWLINE TYPE SPACE CATALOG NEWLINE PAGES SPACE NUM SPACE NUM SPACE STRING NEWLINE GREATERTHAN NEWLINE ENDOBJ NEWLINE NUM SPACE NUM SPACE OBJ NEWLINE LESSTHAN NEWLINE TYPE SPACE FONT NEWLINE SUBTYPE SPACE TYPEONE NEWLINE NAME SPACE FONE NEWLINE BASEFONT SPACE STRING NEWLINE WriteHeader_C0 GREATERTHAN NEWLINE ENDOBJ NEWLINE NUM SPACE NUM SPACE OBJ NEWLINE LESSTHAN NEWLINE FONT SPACE LESSTHAN SPACE FONE SPACE NUM SPACE NUM SPACE STRING SPACE GREATERTHAN NEWLINE PROCSET SPACE ARRAYOPEN SPACE PDFSTRING SPACE TEXTSTRING SPACE ARRAYCLOSE NEWLINE GREATERTHAN NEWLINE ENDOBJ NEWLINE;
PagesSection: WritePages_L0;
STRING_LIST: STRING STRING_LIST | STRING;
TrailerSection: NUM SPACE NUM SPACE OBJ NEWLINE LESSTHAN NEWLINE TYPE SPACE PAGES NEWLINE COUNT SPACE STRING NEWLINE MEDIABOX SPACE ARRAYOPEN SPACE NUM SPACE NUM SPACE STRING SPACE STRING SPACE ARRAYCLOSE NEWLINE KIDS SPACE ARRAYOPEN SPACE STRING SPACE NUM SPACE STRING ARRAYCLOSE NEWLINE GREATERTHAN NEWLINE ENDOBJ NEWLINE XREF NEWLINE NUM SPACE STRING NEWLINE NUM SPACE NUM SPACE STRING SPACE STRING WriteRest_L0 TRAILER NEWLINE LESSTHAN NEWLINE SIZE SPACE STRING NEWLINE ROOT SPACE NUM SPACE NUM SPACE STRING NEWLINE INFO SPACE NUM SPACE NUM SPACE STRING NEWLINE GREATERTHAN NEWLINE STARTXREF NEWLINE STRING NEWLINE STRING NEWLINE;
WriteHeader_C0: ENCODING SPACE LESSTHAN NEWLINE DIFFERENCES SPACE ARRAYOPEN SPACE NUM SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF NEWLINE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF NEWLINE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF NEWLINE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF NEWLINE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF NEWLINE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF NEWLINE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF NEWLINE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE NOTDEF SPACE SLASHWORD SPACE SLASHWORD SPACE NOTDEF NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE ARRAYCLOSE NEWLINE GREATERTHAN NEWLINE | /*empty*/;
WritePages_L0: WritePages_L0_L1 | /*empty*/;
WritePages_L0_L1: WritePages_L0_L1_L2 WritePages_L0_L1_C10 | /*empty*/;
WritePages_L0_L1_C10: NUM SPACE NUM SPACE NUM SPACE NUM SPACE STRING SPACE STRING SPACE STRING NEWLINE | /*empty*/;
WritePages_L0_L1_L2: STRING WritePages_L0_L1_L2_B5_C0 STRING // fallback for any single character STRING NEWLINE WritePages_L0_L1_L2_C3 WritePages_L0_L1_L2_C4 WritePages_L0_L1_L2_C5 WritePages_L0_L1_L2_C6 | /*empty*/;
WritePages_L0_L1_L2_B5_C0: STRING_LIST WritePages_L0_L1_L2_B5_C0_C1 | /*empty*/;
WritePages_L0_L1_L2_B5_C0_C1: SPACE WritePages_L0_L1_L2_B5_C0_C1_C2 | /*empty*/;
WritePages_L0_L1_L2_B5_C0_C1_C2: STRING | /*empty*/;
WritePages_L0_L1_L2_C3:  | /*empty*/;
WritePages_L0_L1_L2_C4:  | /*empty*/;
WritePages_L0_L1_L2_C5:  | /*empty*/;
WritePages_L0_L1_L2_C6: WritePages_L0_L1_L2_C6_C7 WritePages_L0_L1_L2_C6_C8 | WritePages_L0_L1_L2_C6_ELSE_C9;
WritePages_L0_L1_L2_C6_C7:  | /*empty*/;
WritePages_L0_L1_L2_C6_C8:  | /*empty*/;
WritePages_L0_L1_L2_C6_ELSE_C9:  | /*empty*/;
WriteRest_L0: SPACE NUM SPACE STRING SPACE STRING | /*empty*/;

%%

    int main(int argc, char ** argv) {
     #ifdef YYDEBUG
            yydebug = 1;
        #endif
        yyin = fopen(argv[1],"r");
        if (yyin == NULL) {
            fprintf(stderr, "Could not open '%s': %s\n", argv[1] , strerror(errno));
            exit(1);
        }
        yyparse();
        int token;
        while ((token = yylex()) != 0) {
            printf("Token: %d (%s)\n", token, yytext);
        }
        return 0;
    }
    
    void yyerror(const char *s) {
        fprintf(stderr, "Error: %s\n", s);
    }
    