%defines
%locations
%error-verbose

%{
#include <stdio.h>
#include <stddef.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
extern FILE *yyin;
extern char *yytext;
int yylex(void);
void yyerror(const char *s);
%}

%union {
    int ival;
    char* str;
};

/* Tokens */
%token <str> ARRAYCLOSE
%token <str> ARRAYOPEN
%token <str> BASEFONT
%token <str> CATALOG
%token <str> CONTENTS
%token <str> COUNT
%token <str> COURIER
%token <str> CREATIONDATE
%token <str> DIFFERENCES
%token <str> ENCODING
%token <str> ENDOBJ
%token <str> FONE
%token <str> FONT
%token <str> GREATERTHAN
%token <str> INFO
%token <str> KIDS
%token <str> KIDSLOOP
%token <str> LENGTH
%token <str> LESSTHAN
%token <str> LESSTHANNEWLINE
%token <str> MEDIABOX
%token <str> NAME
%token <str> NEWLINE
%token <str> NOTDEF
%token <str> NUM
%token <str> NUMBERLOOP
%token <str> OBJ
%token <str> OBJREF
%token <str> PAGES
%token <str> PARENT
%token <str> PDFDECLARATION
%token <str> PDFSTRING
%token <str> PROCSET
%token <str> PRODUCER
%token <str> RESOURCES
%token <str> ROOT
%token <str> SIZE
%token <str> SLASHWORD
%token <str> SPACE
%token <str> STARTXREF
%token <str> STREAMENDSTREAM
%token <str> STRING
%token <str> SUBTYPE
%token <str> TEXTSTRING
%token <str> TITLE
%token <str> TRAILER
%token <str> TYPE
%token <str> TYPEONE
%token <str> TYPEPAGE
%token <str> XREF

%start main

/* Non-terminals */
%type <str> StartPage
%type <str> WriteHeader
%type <str> WriteHeader_C0
%type <str> WriteHeader_C1
%type <str> WritePages
%type <str> WritePages_C0
%type <str> WritePages_C1
%type <str> WritePages_C10
%type <str> WritePages_C11
%type <str> WritePages_C12
%type <str> WritePages_C13
%type <str> WritePages_C14
%type <str> WritePages_C15
%type <str> WritePages_C16
%type <str> WritePages_C17
%type <str> WritePages_C2
%type <str> WritePages_C3
%type <str> WritePages_C4
%type <str> WritePages_C5
%type <str> WritePages_C6
%type <str> WritePages_C7
%type <str> WritePages_C8
%type <str> WritePages_C9
%type <str> WritePages_L0
%type <str> WritePages_L1
%type <str> WritePages_L2
%type <str> WritePages_L3
%type <str> WriteRest
%type <str> WriteRest_L0
%type <str> WriteRest_L1

%%
main: WriteHeader WritePages WriteRest;
StartPage: STRING SPACE NUM SPACE OBJ NEWLINE LESSTHANNEWLINE TYPE SPACE TYPEPAGE NEWLINE PARENT SPACE NUM SPACE NUM SPACE STRING NEWLINE RESOURCES SPACE NUM SPACE NUM SPACE STRING NEWLINE CONTENTS SPACE STRING SPACE NUM SPACE STRING NEWLINE GREATERTHAN NEWLINE ENDOBJ NEWLINE STRING SPACE NUM SPACE OBJ NEWLINE LESSTHANNEWLINE LENGTH SPACE STRING SPACE NUM SPACE STRING NEWLINE GREATERTHAN NEWLINE STRING NEWLINE STRING NEWLINE FONE SPACE STRING SPACE STRING NEWLINE NUM SPACE NUM SPACE NUM SPACE NUM SPACE NUM SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING NEWLINE;
WriteHeader: PDFDECLARATION NEWLINE NUM SPACE NUM SPACE OBJ NEWLINE LESSTHANNEWLINE CREATIONDATE SPACE STRING NEWLINE PRODUCER SPACE SPACE SPACE STRING SPACE STRING SPACE NEWLINE WriteHeader_C0 GREATERTHAN NEWLINE ENDOBJ NEWLINE NUM SPACE NUM SPACE OBJ NEWLINE LESSTHANNEWLINE TYPE SPACE CATALOG NEWLINE PAGES SPACE NUM SPACE NUM SPACE STRING NEWLINE GREATERTHAN NEWLINE ENDOBJ NEWLINE NUM SPACE NUM SPACE OBJ NEWLINE LESSTHANNEWLINE TYPE SPACE FONT NEWLINE SUBTYPE SPACE TYPEONE NEWLINE NAME SPACE FONE NEWLINE BASEFONT SPACE NEWLINE WriteHeader_C1 GREATERTHAN NEWLINE ENDOBJ NEWLINE NUM SPACE NUM SPACE OBJ NEWLINE LESSTHANNEWLINE SPACE SPACE FONT SPACE LESSTHAN SPACE FONE SPACE NUM SPACE NUM SPACE STRING SPACE GREATERTHAN NEWLINE SPACE SPACE PROCSET SPACE ARRAYOPEN SPACE PDFSTRING SPACE TEXTSTRING SPACE ARRAYCLOSE NEWLINE GREATERTHAN NEWLINE ENDOBJ NEWLINE;
WriteRest: NUM SPACE NUM SPACE OBJ NEWLINE LESSTHANNEWLINE TYPE SPACE PAGES NEWLINE COUNT SPACE STRING NEWLINE MEDIABOX SPACE ARRAYOPEN SPACE NUM SPACE NUM SPACE STRING SPACE STRING SPACE ARRAYCLOSE NEWLINE KIDS SPACE ARRAYOPEN SPACE WriteRest_L0 ARRAYCLOSE NEWLINE GREATERTHAN NEWLINE ENDOBJ NEWLINE XREF NEWLINE NUM SPACE STRING NEWLINE NUM SPACE NUM SPACE STRING SPACE STRING WriteRest_L1 TRAILER NEWLINE LESSTHANNEWLINE SIZE SPACE STRING NEWLINE ROOT SPACE NUM SPACE NUM SPACE STRING NEWLINE INFO SPACE NUM SPACE NUM SPACE STRING NEWLINE GREATERTHAN NEWLINE STARTXREF NEWLINE NEWLINE NEWLINE;
WritePages: WritePages_L0;
WriteHeader_C0: TITLE SPACE STRING NEWLINE | /*empty*/;
WriteHeader_C1: ENCODING SPACE LESSTHAN NEWLINE DIFFERENCES SPACE ARRAYOPEN SPACE NUM SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF NEWLINE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF NEWLINE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF NEWLINE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF NEWLINE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF NEWLINE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF NEWLINE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF NEWLINE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF SPACE NOTDEF NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE NOTDEF SPACE SLASHWORD SPACE SLASHWORD SPACE NOTDEF NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD NEWLINE SLASHWORD SPACE SLASHWORD SPACE SLASHWORD SPACE ARRAYCLOSE NEWLINE GREATERTHAN NEWLINE | /*empty*/;
WritePages_C0: WritePages_C1 STRING WritePages_C2 WritePages_C3 | /*empty*/;
WritePages_C1: STRING | /*empty*/;
WritePages_C10: WritePages_C11 WritePages_C12 WritePages_C13 | /*empty*/;
WritePages_C11: /*empty*/;
WritePages_C12: /*empty*/;
WritePages_C13: /*empty*/;
WritePages_C14: WritePages_C15 WritePages_C16 | /*empty*/;
WritePages_C15: /*empty*/;
WritePages_C16: /*empty*/;
WritePages_C17: NUM SPACE NUM SPACE NUM SPACE NUM SPACE STRING SPACE STRING SPACE STRING NEWLINE | /*empty*/;
WritePages_C2: /*empty*/;
WritePages_C3: WritePages_L3 WritePages_C4 WritePages_C5 | /*empty*/;
WritePages_C4: /*empty*/;
WritePages_C5: STRING WritePages_C6 | /*empty*/;
WritePages_C6: /*empty*/;
WritePages_C7: /*empty*/;
WritePages_C8: /*empty*/;
WritePages_C9: /*empty*/;
WritePages_L0: StartPage WritePages_L1 | /*empty*/;
WritePages_L1: WritePages_L2 WritePages_C17 | /*empty*/;
WritePages_L2: STRING WritePages_C0 NEWLINE WritePages_C7 WritePages_C8 WritePages_C9 WritePages_C10 WritePages_C14 | /*empty*/;
WritePages_L3: SPACE | /*empty*/;
WriteRest_L0: STRING SPACE NUM SPACE STRING | /*empty*/;
WriteRest_L1: SPACE NUM SPACE STRING SPACE STRING | /*empty*/;

%%

int main(int argc, char ** argv) {
 #ifdef YYDEBUG
        yydebug = 1;
    #endif
    yyin = fopen(argv[1],"r");
    if (yyin == NULL) {
        fprintf(stderr, "Could not open '%s': %s\n", argv[1] , strerror(errno));
        exit(1);
    }
    yyparse();
    int token;
    while ((token = yylex()) != 0) {
        printf("Token: %d (%s)\n", token, yytext);
    }
    return 0;
}

void yyerror(const char *s) {
    fprintf(stderr, "Error: %s\n", s);
}
