%defines
%locations
%define parse.error verbose

%{
#include <stdio.h>
#include <stddef.h>
#include <errno.h>
#include <stdlib.h>
extern FILE *yyin;
extern char *yytext;
%}

%union {
    int ival;
    char* str;
}

/* Tokens*/
%token <ival> NUM
%token <str> TITLE MEDIABOX KIDS NUMBERLOOP DIFFERENCES BASEFONT LENGTH PDFDECLARATION NEWLINE CONTENTS TRAILER LESSTHAN SUBTYPE SLASHWORD PRODUCER COUNT CATALOG PROCSET KIDSLOOP FONE ARRAYOPEN SPACE PARENT FONT TYPEPAGE PDFSTRING GREATERTHAN TEXTSTRING ROOT XREF ARRAYCLOSE TYPEONE INFO OBJ NOTDEF CREATIONDATE STREAMENDSTREAM RESOURCES PAGES STARTXREF ENCODING NAME STRING COURIER ENDOBJ SIZE TYPE 


%start main

%%
main: WriteHeader
WriteHeader:PDFDECLARATION NEWLINE NUM SPACE NUM SPACE OBJ NEWLINE LESSTHAN NEWLINE CREATIONDATE SPACE STRING NEWLINE PRODUCER SPACE STRING SPACE NUM SPACE STRING SPACE STRING SPACE NUM NEWLINE yytrovatoreyy OBJ NEWLINE NUM SPACE NUM SPACE OBJ NEWLINE LESSTHAN NEWLINE TYPE SPACE CATALOG NEWLINE PAGES SPACE NUM SPACE NUM SPACE STRING NEWLINE GREATERTHAN NEWLINE OBJ NEWLINE NUM SPACE NUM SPACE OBJ NEWLINE LESSTHAN NEWLINE TYPE SPACE FONT NEWLINE SUBTYPE SPACE TYPE NEWLINE NAME SPACE FONE NEWLINE BASEFONT SPACE STRING NEWLINE yydownplayedyy OBJ NEWLINE NUM SPACE NUM SPACE OBJ NEWLINE LESSTHAN NEWLINE FONT SPACE LESSTHAN SPACE FONE SPACE NUM SPACE NUM SPACE STRING SPACE GREATERTHAN NEWLINE PROCSET SPACE ARRAYOPEN SPACE PDFSTRING SPACE TEXTSTRING SPACE ARRAYCLOSE NEWLINE GREATERTHAN NEWLINE OBJ NEWLINE WritePages
WritePages:yyinfernalityyy yyripelyyy yysupersaintyy yyconsignifyingyy yyepingletteyy yyaraguaneyy yyturbosuperchargedyy yybucklandyy STRING yysarodistyy yyferrumsyy yymacraucheniidyy yycommeasureyy yyboudoiryy 
StartPage:STRING SPACE NUM SPACE OBJ NEWLINE LESSTHAN NEWLINE TYPE SPACE TYPEPAGE NEWLINE PARENT SPACE NUM SPACE NUM SPACE STRING NEWLINE RESOURCES SPACE NUM SPACE NUM SPACE STRING NEWLINE CONTENTS SPACE STRING SPACE NUM SPACE STRING NEWLINE GREATERTHAN NEWLINE OBJ NEWLINE STRING SPACE NUM SPACE OBJ NEWLINE LESSTHAN NEWLINE LENGTH SPACE STRING SPACE NUM SPACE STRING NEWLINE GREATERTHAN NEWLINE STRING NEWLINE STRING NEWLINE FONE SPACE STRING SPACE STRING NEWLINE NUM SPACE NUM SPACE NUM SPACE NUM SPACE NUM SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING NEWLINE EndPage:STRING NEWLINE STRING NEWLINE OBJ NEWLINE STRING SPACE NUM SPACE OBJ NEWLINE STRING NEWLINE OBJ NEWLINE WriteRest
WriteRest:NUM SPACE NUM SPACE OBJ NEWLINE LESSTHAN NEWLINE TYPE SPACE PAGES NEWLINE COUNT SPACE STRING NEWLINE MEDIABOX SPACE ARRAYOPEN SPACE NUM SPACE NUM SPACE STRING SPACE STRING SPACE ARRAYCLOSE NEWLINE KIDS SPACE ARRAYOPEN SPACE yygeminationsyy GREATERTHAN NEWLINE OBJ NEWLINE XREF NEWLINE NUM SPACE STRING NEWLINE yygiantishyy LESSTHAN NEWLINE SIZE SPACE STRING NEWLINE ROOT SPACE NUM SPACE NUM SPACE STRING NEWLINE INFO SPACE NUM SPACE NUM SPACE STRING NEWLINE GREATERTHAN NEWLINE XREF NEWLINE STRING NEWLINE STRING NEWLINE 

yytrovatoreyy: /* empty */ | TITLE SPACE STRING NEWLINE TITLE SPACE STRING NEWLINE 

yydownplayedyy: /* empty */ | ENCODING SPACE LESSTHAN NEWLINE ENCODING SPACE LESSTHAN NEWLINE DIFFERENCES SPACE ARRAYOPEN SPACE NUM SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE ARRAYCLOSE NEWLINE GREATERTHAN NEWLINE 

yymenispermaceaeyy: /* empty */ |   STRING 

yyaraguaneyy: /* empty */ |  
|yyaraguaneyy

yyepingletteyy: /* empty */ |  EndPage 

yyskycraftyy: /* empty */ |  

yygeminationsyy: /* empty */ | STRING SPACE NUM SPACE STRING 
|yygeminationsyy

yygiantishyy: /* empty */ | STRING SPACE NUM SPACE STRING SPACE STRING 
|yygiantishyy

%%

int main(int argc, char ** argv) {
    yyin = fopen(argv[1],"r");
    if (yyin == NULL) {
        fprintf(stderr, "Could not open '%s': %s\n", argv[1] , strerror(errno));
        exit(1);
    }
    yyparse();
    int token;
    while ((token = yylex()) != 0) {
        printf("Token: %d (%s)\n", token, yytext);
    }
    return 0;
}