%defines
%locations
%define parse.error verbose

%{
#include <stdio.h>
#include <stddef.h>
#include <errno.h>
#include <stdlib.h>
extern FILE *yyin;
extern char *yytext;
%}

%union {
    int ival;
    char* str;
}

/* Tokens*/
%token <ival> NUM
%token <str> ENCODING GREATERTHAN ARRAYOPEN COURIER ENDOBJ LESSTHAN LENGTH MEDIABOX TITLE PRODUCER KIDSLOOP NAME PDFSTRING TYPEONE PROCSET PARENT KIDS RESOURCES FONE CREATIONDATE NEWLINE TYPEPAGE BASEFONT ARRAYCLOSE ROOT SPACE NUMBERLOOP TEXTSTRING CONTENTS PAGES COUNT XREF STRING DIFFERENCES SUBTYPE SLASHWORD STARTXREF SIZE FONT PDFDECLARATION TRAILER OBJ INFO CATALOG NOTDEF STREAMENDSTREAM TYPE 


%start main

%%
main:  WriteHeader
WriteHeader:PDFDECLARATION NEWLINE NUM SPACE NUM SPACE OBJ NEWLINE LESSTHAN NEWLINE CREATIONDATE SPACE STRING NEWLINE PRODUCER SPACE STRING SPACE NUM SPACE STRING SPACE STRING SPACE NUM NEWLINE yyoneyy GREATERTHAN NEWLINE OBJ NEWLINE NUM SPACE NUM SPACE OBJ NEWLINE LESSTHAN NEWLINE TYPE SPACE CATALOG NEWLINE PAGES SPACE NUM SPACE NUM SPACE STRING NEWLINE GREATERTHAN NEWLINE OBJ NEWLINE NUM SPACE NUM SPACE OBJ NEWLINE LESSTHAN NEWLINE TYPE SPACE FONT NEWLINE SUBTYPE SPACE TYPE NEWLINE NAME SPACE FONE NEWLINE BASEFONT SPACE STRING NEWLINE yyoneyy GREATERTHAN NEWLINE OBJ NEWLINE NUM SPACE NUM SPACE OBJ NEWLINE LESSTHAN NEWLINE FONT SPACE LESSTHAN SPACE FONE SPACE NUM SPACE NUM SPACE STRING SPACE GREATERTHAN NEWLINE PROCSET SPACE ARRAYOPEN SPACE PDFSTRING SPACE TEXTSTRING SPACE ARRAYCLOSE NEWLINE GREATERTHAN NEWLINE OBJ NEWLINE  WritePages
WritePages:yytwoyy yytwoyy NEWLINE NEWLINE yytwoyy  WriteRest
WriteRest:NUM SPACE NUM SPACE OBJ NEWLINE LESSTHAN NEWLINE TYPE SPACE PAGES NEWLINE COUNT SPACE STRING NEWLINE MEDIABOX SPACE ARRAYOPEN SPACE NUM SPACE NUM SPACE STRING SPACE STRING SPACE ARRAYCLOSE NEWLINE KIDS SPACE ARRAYOPEN SPACE STRING SPACE NUM SPACE STRING ARRAYCLOSE NEWLINE GREATERTHAN NEWLINE OBJ NEWLINE XREF NEWLINE NUM SPACE STRING NEWLINE STRING SPACE NUM SPACE STRING SPACE STRING TRAILER NEWLINE LESSTHAN NEWLINE SIZE SPACE STRING NEWLINE ROOT SPACE NUM SPACE NUM SPACE STRING NEWLINE INFO SPACE NUM SPACE NUM SPACE STRING NEWLINE GREATERTHAN NEWLINE XREF NEWLINE STRING NEWLINE STRING NEWLINE 

yyoneyy: /* empty */ | TITLE SPACE STRING NEWLINE  | ENCODING SPACE LESSTHAN NEWLINE DIFFERENCES SPACE ARRAYOPEN SPACE NUM SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING SPACE STRING NEWLINE STRING SPACE STRING SPACE STRING SPACE ARRAYCLOSE NEWLINE GREATERTHAN NEWLINE 

yytwoyy: /* empty */ |  STRING   | STRING  | NUM SPACE NUM SPACE NUM SPACE NUM SPACE STRING SPACE STRING SPACE STRING NEWLINE 

yythreeyy: /* empty */ | 

%%

int main(int argc, char ** argv) {
    yyin = fopen(argv[1],"r");
    if (yyin == NULL) {
        fprintf(stderr, "Could not open '%s': %s\n", argv[1] , strerror(errno));
        exit(1);
    }
    yyparse();
    int token;
    while ((token = yylex()) != 0) {
        printf("Token: %d (%s)\n", token, yytext);
    }
    return 0;
}